Importing Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [38]:
credit_data=pd.read_csv("/content/creditcard.csv")

In [39]:
credit_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [40]:
credit_data.shape

(284807, 31)

In [41]:
credit_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [42]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [43]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [44]:
#distribution of legit transactions & fraudulent transactions
credit_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [45]:
#seperating the data for analysis
legit=credit_data[credit_data.Class==0]
fraud=credit_data[credit_data.Class==1]

In [46]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [47]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [48]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [49]:
credit_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [51]:
legit_sample=legit.sample(n=492)

In [52]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [53]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
222021,142790.0,1.958661,-0.672023,-0.462776,0.315267,-0.741171,-0.053214,-0.871412,0.238552,1.323204,...,0.204478,0.681585,0.099376,-0.458568,-0.288596,0.630426,-0.038650,-0.067467,13.97,0
204105,135112.0,2.116842,-0.066778,-1.793179,-0.082775,0.734055,-0.122663,0.101947,-0.163739,0.374048,...,0.233462,0.853970,-0.183109,-1.390025,0.413896,-0.032868,-0.014411,-0.080936,1.00,0
261198,159911.0,-4.952053,4.613081,-4.435697,-0.735361,-2.017633,-1.323602,-1.937387,3.406285,0.462028,...,-0.302707,-1.119822,0.530802,0.473163,0.266942,0.176505,0.268691,0.205106,8.99,0
181163,124854.0,2.268389,-0.539501,-1.708994,-1.086935,0.000871,-1.019387,-0.064369,-0.455671,-0.799344,...,0.020654,0.062712,0.111477,-0.748338,0.053283,-0.268229,-0.040034,-0.067370,17.88,0
168188,119104.0,0.468099,-2.905449,-1.678267,0.811208,-1.131000,-0.172565,0.685012,-0.228652,0.616366,...,0.492252,-0.282076,-0.518948,-0.264675,-0.580480,0.454823,-0.212775,0.069220,805.09,0

In [54]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [55]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [56]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95039.882114,0.010488,-0.141071,-0.006642,-0.015340,-0.007171,-0.068364,-0.096940,-0.008840,-0.010551,...,0.033238,0.021816,-0.032480,0.005272,0.006667,-0.002833,0.002238,-0.009390,0.012796,95.849858
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [57]:
#Splitting the data into Features and Targets
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [58]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
222021  142790.0  1.958661 -0.672023 -0.462776  0.315267 -0.741171 -0.053214
204105  135112.0  2.116842 -0.066778 -1.793179 -0.082775  0.734055 -0.122663
261198  159911.0 -4.952053  4.613081 -4.435697 -0.735361 -2.017633 -1.323602
181163  124854.0  2.268389 -0.539501 -1.708994 -1.086935  0.000871 -1.019387
168188  119104.0  0.468099 -2.905449 -1.678267  0.811208 -1.131000 -0.172565
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
222021 -0.871412  0.238552  1.323204  ... -0.305284  0.204478  0.681585
204105  0.101947 -0.163739  0.374048  ... -0.155613  0.233462  0.853970
261198 -1.937387  3.406285  0.462028  ...  0.438129 -0.302707 -1.119822
181163 -0.064369 -0.455671 -0.799344  ...  0.050947  0.020654  0.062712
168188  0.685012 -0.228652  0.616366  ...  1.423395  0.492252 -0.282076
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
222021  0.099376 -0.458568 -0.288596  0.630426 -0.038650 -0.067467   13.97
204105 -0.183109 -1.390025  0.413896 -0.032868 -0.014411 -0.080936    1.00
261198  0.530802  0.473163  0.266942  0.176505  0.268691  0.205106    8.99
181163  0.111477 -0.748338  0.053283 -0.268229 -0.040034 -0.067370   17.88
168188 -0.518948 -0.264675 -0.580480  0.454823 -0.212775  0.069220  805.09
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [59]:
print(Y)

222021    0
204105    0
261198    0
181163    0
168188    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [60]:
X_train,X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y, random_state=2)

In [61]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [62]:
model=LogisticRegression()

In [63]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [64]:
#Accuracy on training data
X_train_prediction=model.predict(X_train)
accu=accuracy_score(X_train_prediction,Y_train)

In [65]:
accu

0.9428208386277002

In [66]:
#Accuracy on testing data
X_test_prediction=model.predict(X_test)
accu2=accuracy_score(X_test_prediction,Y_test)

In [67]:
accu2

0.9441624365482234